<a href="https://colab.research.google.com/github/ayushjaiswal21/-90DayML/blob/main/pytorch_tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pprint # For pretty printing large outputs if needed

In [3]:
# --- 2. Initializing Tensors ---

print("--- 2. Initializing Tensors ---")

# 2.1. From Python List / NumPy Array
print("2.1. From Python List / NumPy Array:")
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from list:\n{x_data}")

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy array:\n{x_np}")
print(f"Data type of x_np: {x_np.dtype}\n")


--- 2. Initializing Tensors ---
2.1. From Python List / NumPy Array:
Tensor from list:
tensor([[1, 2],
        [3, 4]])
Tensor from NumPy array:
tensor([[1, 2],
        [3, 4]])
Data type of x_np: torch.int64



In [6]:
if torch.cuda.is_available():
    device = "cuda"
    print(f"GPU is available! Using device: {torch.cuda.get_device_name(0)}")
else:
    device = "cpu"
    print("GPU not available. Using CPU.")

print(f"All tensors will be created on: {device}\n")-

GPU is available! Using device: Tesla T4
All tensors will be created on: cuda



In [4]:
# 2.2. With specific values / shapes
print("2.2. With specific values / shapes:")
x_ones = torch.ones(2, 3) # 2 rows, 3 columns, filled with ones
print(f"Tensor of ones (2x3):\n{x_ones}")

x_zeros = torch.zeros(3, 2) # 3 rows, 2 columns, filled with zeros
print(f"Tensor of zeros (3x2):\n{x_zeros}")

x_rand = torch.rand(2, 2) # 2x2 tensor with random values from a uniform distribution [0, 1)
print(f"Tensor of randoms (2x2):\n{x_rand}")

x_randn = torch.randn(2, 2) # 2x2 tensor with random values from a standard normal distribution (mean=0, std=1)
print(f"Tensor of random normal (2x2):\n{x_randn}\n")

2.2. With specific values / shapes:
Tensor of ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor of zeros (3x2):
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
Tensor of randoms (2x2):
tensor([[0.3207, 0.2790],
        [0.2799, 0.9726]])
Tensor of random normal (2x2):
tensor([[ 0.5428,  0.7513],
        [-0.7481, -0.9388]])



In [7]:
# 2.3. Like existing tensors (retains properties like shape, dtype, device)
print("2.3. Like existing tensors:")
x_data_on_device = x_data.to(device) # Move x_data to the selected device

x_ones_like = torch.ones_like(x_data_on_device) # Creates a tensor of ones with the same properties as x_data_on_device
print(f"Tensor of ones like x_data_on_device:\n{x_ones_like}")
print(f"Device of x_ones_like: {x_ones_like.device}\n")

x_rand_like = torch.rand_like(x_data_on_device, dtype=torch.float) # Can also override properties
print(f"Tensor of randoms like x_data_on_device (float):\n{x_rand_like}")
print(f"Data type of x_rand_like: {x_rand_like.dtype}\n")


2.3. Like existing tensors:
Tensor of ones like x_data_on_device:
tensor([[1, 1],
        [1, 1]], device='cuda:0')
Device of x_ones_like: cuda:0

Tensor of randoms like x_data_on_device (float):
tensor([[0.8094, 0.1379],
        [0.1031, 0.1268]], device='cuda:0')
Data type of x_rand_like: torch.float32



In [8]:
print("--- 3. Tensor Attributes ---")

tensor = torch.rand(3, 4)
print(f"Original tensor:\n{tensor}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Data type of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}\n")

# Move the tensor to GPU if available and observe device change
if device == "cuda":
    tensor_gpu = tensor.to("cuda")
    print(f"Tensor moved to GPU:\n{tensor_gpu}")
    print(f"Device tensor_gpu is stored on: {tensor_gpu.device}\n")


--- 3. Tensor Attributes ---
Original tensor:
tensor([[0.3210, 0.1393, 0.7949, 0.3036],
        [0.9314, 0.1329, 0.0200, 0.5702],
        [0.4257, 0.0844, 0.7843, 0.9357]])
Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu

Tensor moved to GPU:
tensor([[0.3210, 0.1393, 0.7949, 0.3036],
        [0.9314, 0.1329, 0.0200, 0.5702],
        [0.4257, 0.0844, 0.7843, 0.9357]], device='cuda:0')
Device tensor_gpu is stored on: cuda:0



In [9]:
# --- 4. Operations on Tensors ---

print("--- 4. Operations on Tensors ---")

# Ensure tensors are on the same device for operations
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32).to(device)
tensor_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32).to(device)

print(f"Tensor A:\n{tensor_a}")
print(f"Tensor B:\n{tensor_b}\n")

--- 4. Operations on Tensors ---
Tensor A:
tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
Tensor B:
tensor([[5., 6.],
        [7., 8.]], device='cuda:0')



In [10]:

# 4.1. Arithmetic Operations
print("4.1. Arithmetic Operations:")
print(f"Addition (A + B):\n{tensor_a + tensor_b}")
print(f"Addition (torch.add(A, B)):\n{torch.add(tensor_a, tensor_b)}")
print(f"Subtraction (A - B):\n{tensor_a - tensor_b}")
print(f"Multiplication (element-wise A * B):\n{tensor_a * tensor_b}")
print(f"Division (element-wise A / B):\n{tensor_a / tensor_b}")
print(f"Exponentiation (A**2):\n{tensor_a**2}\n")

4.1. Arithmetic Operations:
Addition (A + B):
tensor([[ 6.,  8.],
        [10., 12.]], device='cuda:0')
Addition (torch.add(A, B)):
tensor([[ 6.,  8.],
        [10., 12.]], device='cuda:0')
Subtraction (A - B):
tensor([[-4., -4.],
        [-4., -4.]], device='cuda:0')
Multiplication (element-wise A * B):
tensor([[ 5., 12.],
        [21., 32.]], device='cuda:0')
Division (element-wise A / B):
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]], device='cuda:0')
Exponentiation (A**2):
tensor([[ 1.,  4.],
        [ 9., 16.]], device='cuda:0')



In [12]:
# 4.2. Matrix Multiplication
print("4.2. Matrix Multiplication:")
matrix_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32).to(device) # 2x2
matrix_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32).to(device) # 2x2
# Both methods produce the same result for matrix multiplication
print(f"Matrix multiplication (A @ B):\n{matrix_a @ matrix_b}")
print(f"Matrix multiplication (torch.matmul(A, B)):\n{torch.matmul(matrix_a, matrix_b)}\n")

# Example with different shapes (requires valid matrix multiplication rules)
# (1x2) @ (2x3) -> (1x3)
vec_a = torch.tensor([1, 2], dtype=torch.float32).to(device) # 1D tensor is treated as 1xN or Nx1 for matmul
matrix_c = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32).to(device) # 2x3

# For 1D tensors, torch.matmul implicitly adds dimensions.
# It's safer to explicitly reshape if unsure.
# Here, vec_a is treated as (1, 2)
result_matmul = torch.matmul(vec_a, matrix_c)
print(f"Vector (1x2) @ Matrix (2x3):\n{result_matmul}")
print(f"Shape of result: {result_matmul.shape}\n")


4.2. Matrix Multiplication:
Matrix multiplication (A @ B):
tensor([[19., 22.],
        [43., 50.]], device='cuda:0')
Matrix multiplication (torch.matmul(A, B)):
tensor([[19., 22.],
        [43., 50.]], device='cuda:0')

Vector (1x2) @ Matrix (2x3):
tensor([ 9., 12., 15.], device='cuda:0')
Shape of result: torch.Size([3])



In [13]:
# 4.3. In-place Operations (modify the tensor without creating a new one)
print("4.3. In-place Operations:")
tensor_inplace = torch.ones(2, 2).to(device)
print(f"Original tensor_inplace:\n{tensor_inplace}")
tensor_inplace.add_(5) # Note the underscore! This modifies tensor_inplace directly.
print(f"tensor_inplace after add_(5):\n{tensor_inplace}\n")

4.3. In-place Operations:
Original tensor_inplace:
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor_inplace after add_(5):
tensor([[6., 6.],
        [6., 6.]], device='cuda:0')



In [14]:
# 4.4. Indexing and Slicing (similar to NumPy)
print("4.4. Indexing and Slicing:")
indexing_tensor = torch.tensor([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33],
    [40, 41, 42, 43]
]).to(device)
print(f"Original indexing_tensor:\n{indexing_tensor}\n")

print(f"First row: {indexing_tensor[0]}")
print(f"Last column: {indexing_tensor[:, -1]}")
print(f"Element at (1, 2): {indexing_tensor[1, 2]}")
print(f"Sub-tensor (rows 0-1, cols 1-2):\n{indexing_tensor[0:2, 1:3]}\n")

4.4. Indexing and Slicing:
Original indexing_tensor:
tensor([[10, 11, 12, 13],
        [20, 21, 22, 23],
        [30, 31, 32, 33],
        [40, 41, 42, 43]], device='cuda:0')

First row: tensor([10, 11, 12, 13], device='cuda:0')
Last column: tensor([13, 23, 33, 43], device='cuda:0')
Element at (1, 2): 22
Sub-tensor (rows 0-1, cols 1-2):
tensor([[11, 12],
        [21, 22]], device='cuda:0')



In [15]:
# 4.5. Reshaping and Squeezing/Unsqueezing
print("4.5. Reshaping and Squeezing/Unsqueezing:")
x_reshape = torch.arange(9).to(device) # Creates a tensor [0, 1, ..., 8]
print(f"Original 1D tensor (arange(9)):\n{x_reshape}")
print(f"Shape: {x_reshape.shape}")

# Reshape to a 3x3 matrix
x_reshaped = x_reshape.view(3, 3) # view() requires contiguous memory, reshape() is more flexible
print(f"Reshaped to 3x3:\n{x_reshaped}")
print(f"Shape: {x_reshaped.shape}\n")

# Add a dimension (unsqueeze) - useful for batching or specific layer inputs
x_unsqueeze = x_reshaped.unsqueeze(0) # Adds a dimension at position 0 (batch dimension)
print(f"Unsqueezed (adds a dim at 0):\n{x_unsqueeze}")
print(f"Shape after unsqueeze(0): {x_unsqueeze.shape}\n") # (1, 3, 3)

# Remove a dimension of size 1 (squeeze)
x_squeeze = x_unsqueeze.squeeze(0) # Removes the dimension at position 0 if its size is 1
print(f"Squeezed (removes dim at 0):\n{x_squeeze}")
print(f"Shape after squeeze(0): {x_squeeze.shape}\n") # (3, 3)



4.5. Reshaping and Squeezing/Unsqueezing:
Original 1D tensor (arange(9)):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], device='cuda:0')
Shape: torch.Size([9])
Reshaped to 3x3:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], device='cuda:0')
Shape: torch.Size([3, 3])

Unsqueezed (adds a dim at 0):
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]], device='cuda:0')
Shape after unsqueeze(0): torch.Size([1, 3, 3])

Squeezed (removes dim at 0):
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], device='cuda:0')
Shape after squeeze(0): torch.Size([3, 3])



In [16]:
# 4.6. Concatenation and Stacking
print("4.6. Concatenation and Stacking:")
tensor1 = torch.ones(2, 2).to(device)
tensor2 = torch.zeros(2, 2).to(device)
print(f"Tensor 1:\n{tensor1}")
print(f"Tensor 2:\n{tensor2}\n")

# Concatenate along dimension 0 (rows)
concatenated_rows = torch.cat([tensor1, tensor2], dim=0)
print(f"Concatenated along dim 0 (rows):\n{concatenated_rows}")
print(f"Shape: {concatenated_rows.shape}\n") # (4, 2)

# Concatenate along dimension 1 (columns)
concatenated_cols = torch.cat([tensor1, tensor2], dim=1)
print(f"Concatenated along dim 1 (columns):\n{concatenated_cols}")
print(f"Shape: {concatenated_cols.shape}\n") # (2, 4)

# Stacking creates a new dimension
stacked_tensors = torch.stack([tensor1, tensor2], dim=0)
print(f"Stacked along dim 0:\n{stacked_tensors}")
print(f"Shape: {stacked_tensors.shape}\n") # (2, 2, 2)

4.6. Concatenation and Stacking:
Tensor 1:
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
Tensor 2:
tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

Concatenated along dim 0 (rows):
tensor([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]], device='cuda:0')
Shape: torch.Size([4, 2])

Concatenated along dim 1 (columns):
tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.]], device='cuda:0')
Shape: torch.Size([2, 4])

Stacked along dim 0:
tensor([[[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]], device='cuda:0')
Shape: torch.Size([2, 2, 2])



In [17]:
print("--- 5. Bridge with NumPy ---")

# 5.1. PyTorch Tensor to NumPy Array
print("5.1. PyTorch Tensor to NumPy Array:")
torch_tensor = torch.ones(5).to(device) # Can be on CPU or GPU initially
print(f"PyTorch Tensor:\n{torch_tensor}")
print(f"Device of PyTorch Tensor: {torch_tensor.device}")

# If tensor is on GPU, it must be moved to CPU before converting to NumPy
if torch_tensor.is_cuda:
    numpy_array_from_torch = torch_tensor.cpu().numpy()
else:
    numpy_array_from_torch = torch_tensor.numpy()

print(f"NumPy Array from Tensor:\n{numpy_array_from_torch}")
print(f"Type of NumPy Array: {type(numpy_array_from_torch)}\n")


--- 5. Bridge with NumPy ---
5.1. PyTorch Tensor to NumPy Array:
PyTorch Tensor:
tensor([1., 1., 1., 1., 1.], device='cuda:0')
Device of PyTorch Tensor: cuda:0
NumPy Array from Tensor:
[1. 1. 1. 1. 1.]
Type of NumPy Array: <class 'numpy.ndarray'>



In [18]:
# 5.2. NumPy Array to PyTorch Tensor
print("5.2. NumPy Array to PyTorch Tensor:")
numpy_array = np.ones(5)
torch_tensor_from_numpy = torch.from_numpy(numpy_array).to(device) # Move to device after creation
print(f"NumPy Array:\n{numpy_array}")
print(f"PyTorch Tensor from NumPy:\n{torch_tensor_from_numpy}")
print(f"Device of PyTorch Tensor from NumPy: {torch_tensor_from_numpy.device}\n")


5.2. NumPy Array to PyTorch Tensor:
NumPy Array:
[1. 1. 1. 1. 1.]
PyTorch Tensor from NumPy:
tensor([1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)
Device of PyTorch Tensor from NumPy: cuda:0



In [19]:
# 5.3. Shared Memory between CPU Tensors and NumPy Arrays
print("5.3. Shared Memory between CPU Tensors and NumPy Arrays:")
# IMPORTANT: This only happens when converting CPU tensors.
# If a tensor is on GPU, it's copied to CPU first for conversion, breaking the shared memory.
cpu_numpy_array = np.arange(5)
cpu_torch_tensor = torch.from_numpy(cpu_numpy_array)

print(f"Original NumPy Array: {cpu_numpy_array}")
print(f"Original PyTorch Tensor (from NumPy): {cpu_torch_tensor}")

# Modify the NumPy array
cpu_numpy_array[0] = 99
print(f"NumPy Array after modification: {cpu_numpy_array}")
print(f"PyTorch Tensor (observe change, as memory is shared): {cpu_torch_tensor}\n")

# Modify the PyTorch tensor
cpu_torch_tensor[1] = 88
print(f"PyTorch Tensor after modification: {cpu_torch_tensor}")
print(f"NumPy Array (observe change, as memory is shared): {cpu_numpy_array}\n")

# --- End of Notebook ---
print("--- End of PyTorch Tensors Fundamentals Notebook ---")

5.3. Shared Memory between CPU Tensors and NumPy Arrays:
Original NumPy Array: [0 1 2 3 4]
Original PyTorch Tensor (from NumPy): tensor([0, 1, 2, 3, 4])
NumPy Array after modification: [99  1  2  3  4]
PyTorch Tensor (observe change, as memory is shared): tensor([99,  1,  2,  3,  4])

PyTorch Tensor after modification: tensor([99, 88,  2,  3,  4])
NumPy Array (observe change, as memory is shared): [99 88  2  3  4]

--- End of PyTorch Tensors Fundamentals Notebook ---
